name: CI

on:
  push:
    branches:
      - master
      - develop
    tags:
      - "**"
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest
    name: Build Repository
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Set up JDK 8
      uses: actions/setup-java@v1
      with:
        java-version: 8
    - name: Setup Maven
      run: echo "MAVEN_OPTS='-Xmx2048m'" > ~/.mavenrc
    - name: Cache maven repo
      uses: actions/cache@v2
      env:
        cache-name: cache-maven-repo
      with:
        # maven files are stored in `~/.m2/repository` on Linux/macOS
        path: |
          ~/.m2/repository
          !~/.m2/repository/org/platformio/eclipse/ide
          !~/.m2/repository/.cache/tycho
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/*.sha1') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-
    - name: Build with Maven
      run: mvn clean verify --no-transfer-progress -U

    - name: Archive snapshot
      if: ${{ github.event_name == 'push' }}
      run: |
        tar -C ./releng/org.platformio.eclipse.ide.repository/target -czvf repository.tar.gz repository

    - name: Preserve snapshot
      if: ${{ github.event_name == 'push' }}
      uses: actions/upload-artifact@v2
      with:
        name: snapshot
        path: ./repository.tar.gz

  deploy:

    name: Deploy to Github Pages
    needs: build
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: snapshot

      - name: Prepare Composite
        run: |
          mkdir ./composite
          tar -xzf ./repository.tar.gz -C ./composite
          cp ./releng/org.platformio.eclipse.ide.releng/compositeArtifacts.xml ./composite
          cp ./releng/org.platformio.eclipse.ide.releng/compositeContent.xml ./composite

      - name: Detect build type
        id: get-destination-dir
        env:
          RELEASE_BUILD: ${{ startsWith(github.ref, 'refs/tags/v') }}
        run: |
          if ${RELEASE_BUILD} == true; then
            echo "::set-output name=destination_dir::release"
          else
            echo "::set-output name=destination_dir::integration"
          fi

      - name: Deploy to Github Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./composite
          destination_dir: ${{ steps.get-destination-dir.outputs.destination_dir }}
          cname: eclipse.dl.platformio.org
          keep_files: true

      - name: Delete Artifact
        uses: geekyeggo/delete-artifact@v1
        with:
          name: snapshot
